### ISSUE TITLE
Swagger documentation

### ISSUE THREAD

**Issue by techseria** [openboxes/openboxes#1129]
Do you have swagger documents?

**Comment by jmiranda** [comment]
I've explored adding Swagger / OpenAPI but it was a bit overwhelming, so I put that project on hold. It would be amazing if we could add it to the project, so I'd be thrilled if you guys were interested in making that happen. Even for a single endpoint. 

If you're interested, here are the existing API docs:
http://docs.openboxes.com/en/latest/api-guide/

**Comment by jmiranda** [comment]
If you want some other ideas for projects, check out the Roadmap Ideas ticket https://github.com/openboxes/openboxes/issues/169. This includes some of the more fun / interesting projects that I haven't had a chance to work on yet.

**Comment by jmiranda** [comment]
We published our OpenAPI docs to swaggerhub a few months back. There's still a fair amount of work to be done, but I think we can close this ticket for now. 
https://app.swaggerhub.com/apis-docs/openboxes/api/0.8.17
