### ISSUE TITLE
Error executing script RunApp: java.io.IOException: Cannot run program "npm" The system cannot find the file specified

### ISSUE THREAD

**Issue by wangpengxpy** [openboxes/openboxes#1193]
for release 0.8.8 Hotfix 2 version.

I installed node locally and idea configures node plugin,the follow

![image](https://user-images.githubusercontent.com/12961992/62999435-fcfd1500-bea0-11e9-8396-e6dd7f3f1dbe.png)
![image](https://user-images.githubusercontent.com/12961992/62999456-14d49900-bea1-11e9-9980-2f3c3f4597fa.png)

but throw the following error
![image](https://user-images.githubusercontent.com/12961992/62999341-b9a2a680-bea0-11e9-868d-c25c242b7a11.png)

I don't know where the problem is. Is't  a version issue for node?
thanks in advance

**Comment by jmiranda** [comment]
It's probably not an NPM version issue but rather an issue with Windows. I'm not exactly sure how to solve it but here's a StackOverflow post that addresses the issue.
https://stackoverflow.com/questions/22708255/cannot-run-program-npm-in-directory

**Comment by jmiranda** [comment]
Here's one that might also be helpful. Just be sure to research what it means to use the EnableExtensions feature. I don't want to open a security hole on your machine. 
https://github.com/nodejs/help/issues/379

**Comment by wangpengxpy** [comment]
@jmiranda   thanks your reply quickly

According to the solution you provided
![image](https://user-images.githubusercontent.com/12961992/63066363-50707100-bf3c-11e9-9eef-5e59b4b85396.png)

but when i view the  EnableExetensions property for windows 10,the default value is 1 ,no need to change.

![image](https://user-images.githubusercontent.com/12961992/63066490-f02dff00-bf3c-11e9-8041-6fa222dde12a.png)

What other ideas do you have for it?

**Comment by jmiranda** [comment]
@wangpengxpy Sorry for not responding last week. I was working on a large issue that required most of my attention. I just noticed that you closed this ticket and wanted to make sure that you found a solution. If not, I can probably continue to investigate the issue tomorrow morning.

**Comment by wangpengxpy** [comment]
@jmiranda  Hi,Thank you for taking the time to follow up on my problem.
The problem is that execute npm command in【_Events.groovy】the follow:

    def command = """npm run bundle"""
    def proc = cmd.execute()

It caused by npm command path not found,but according to the above mentioned by me,I have installed node correctly. finally, I temporarily modified the code below. it works

    String[] cmd = ["C:/Program Files/nodejs/node.exe", "npm run bundle"] as String[];
    def proc = cmd.execute()

Please investigate why the npm execution path cannot be found. i think other developers will encounter the same problems in the developmen environment.thks
