### ISSUE TITLE
Cannot start 0.8.9-hf1

### ISSUE THREAD

**Issue by jakkarth** [openboxes/openboxes#1266]
Using 0.8.9-hf1

Actual behavior:

Openboxes will not start. Validation failed for a changeset checksum. Reproducible every time.

Expected behavior:

0.8.9-hf1 should start, since 0.8.9 starts ok.

Workaround:

Roll back to 0.8.9. No issues starting with that version even after trying to start this one.

Additional information:

tomcat_1  | 2019-10-10 11:56:23,220 [localhost-startStop-1] INFO  liquibase  - Successfully acquired change log lock                                                                                                          [111/1848]
tomcat_1  | 2019-10-10 11:56:25,411 [localhost-startStop-1] INFO  liquibase  - Release Database Lock        
tomcat_1  | 2019-10-10 11:56:25,492 [localhost-startStop-1] INFO  liquibase  - Successfully released change log lock                                                                                     
tomcat_1  | 2019-10-10 11:56:25,506 [localhost-startStop-1] ERROR context.ContextLoader  - Context initialization failed                                                                                                                tomcat_1  | org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is org.codehaus.groovy.runtime.InvokerInvocationException: liquibase.exception.ValidationFailedException: Validati
on Failed:                                                                                                             
tomcat_1  |      1 change sets check sum                                                                                                                                                                       
tomcat_1  |           0.8.x/changelog-2019-08-15-1229-alter-table-inventory-snapshot-add-unique-index.xml::1565890211110-1::jmiranda (generated)::(MD5Sum: b04ed37539813ec408d68f62ac22e8e)
tomcat_1  |                                                                                                                                                                                            
tomcat_1  |     at org.codehaus.groovy.grails.web.context.GrailsContextLoader.createWebApplicationContext(GrailsContextLoader.java:87)
tomcat_1  |     at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)                                                                                   
tomcat_1  |     at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)      
tomcat_1  |     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5197)                                                                                                                  
tomcat_1  |     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5720)                              
tomcat_1  |     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)                                                                                                               
tomcat_1  |     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)                        
tomcat_1  |     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)                                                                                                              
tomcat_1  |     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)                      
tomcat_1  |     at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)                                                                                                            
tomcat_1  |     at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)                                    
tomcat_1  |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)                                                                                                           
tomcat_1  |     at java.util.concurrent.FutureTask.run(FutureTask.java:262)                                  
tomcat_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)                                                                                                   
tomcat_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)                
tomcat_1  |     at java.lang.Thread.run(Thread.java:748)                                                                                                                                             
tomcat_1  | Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: liquibase.exception.ValidationFailedException: Validation Failed:
tomcat_1  |      1 change sets check sum                                                                                                                                                             
tomcat_1  |           0.8.x/changelog-2019-08-15-1229-alter-table-inventory-snapshot-add-unique-index.xml::1565890211110-1::jmiranda (generated)::(MD5Sum: b04ed37539813ec408d68f62ac22e8e)
tomcat_1  |                                                                                                                                                                                          
tomcat_1  |     at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:251)                                            
tomcat_1  |     at grails.util.Environment.executeForEnvironment(Environment.java:244)                                                                                                                                                  tomcat_1  |     at grails.util.Environment.executeForCurrentEnvironment(Environment.java:220)                                                                                       
tomcat_1  |     ... 5 more                                                                                                                                                                           
tomcat_1  | Caused by: liquibase.exception.ValidationFailedException: Validation Failed:                       
tomcat_1  |      1 change sets check sum                                                                                                                                                             
tomcat_1  |           0.8.x/changelog-2019-08-15-1229-alter-table-inventory-snapshot-add-unique-index.xml::1565890211110-1::jmiranda (generated)::(MD5Sum: b04ed37539813ec408d68f62ac22e8e)
tomcat_1  |                                                                                                                                                                                           
tomcat_1  |     at liquibase.DatabaseChangeLog.validate(DatabaseChangeLog.java:119)                         
tomcat_1  |     at liquibase.Liquibase.update(Liquibase.java:106)                                                                                                                                              
tomcat_1  |     at liquibase.Liquibase$update.call(Unknown Source)                                                 
tomcat_1  |     at BootStrap$_closure1.doCall(BootStrap.groovy:454)                                                                                                                                         
tomcat_1  |     ... 8 more

**Comment by jmiranda** [comment]
@jakkarth Thanks, I'll take a look. There's already a fix for this merged to develop. I didn't think it affected master, but will get that merged over and push up a new hotfix.

**Comment by jmiranda** [comment]
@jakkarth I'm trying to figure out how this happened so quick question: over the course of the last few weeks, did you deploy a nightly snapshot version from Bamboo prior to deploying this hotfix?

**Comment by jmiranda** [comment]
Actually, ignore that ... it doesn't actually matter if you did or not. The checksum is based on the content of the changeset, so it doesn't care what's in your databasechangelog.

**Comment by jakkarth** [comment]
Negative. I had 0.8.9 deployed from the github release page, and then I deployed 0.8.9-hf1 from the gitlab release page. I haven't used a bamboo build for a while.

**Comment by jmiranda** [comment]
Fixed in develop. Need to cherry-pick this commit into master.
https://github.com/openboxes/openboxes/commit/47d4335644cfc3a48fcd7033d5f824dfbfea0a00

**Comment by jakkarth** [comment]
Is a new .war forthcoming?

**Comment by jmiranda** [comment]
Awesome. I was just coming here to let you know that the new hotfix release was created on GitHub based on that Bamboo artifact you downloaded.
