### ISSUE TITLE
Add the ability for address in delivery note

### ISSUE THREAD

**Issue by pacomms** [openboxes/openboxes#1422]
We woud like the ability to be able to have the delivery address printed on the delivery note as we use these as notes in docs enclosed on parcels, probably be best to add this under where it says delivery note and the barcode, then it can be folded and used as delivery note, also can the text be in bold and the size of the deliverynote text..

Thanks
K

**Comment by jmiranda** [comment]
@pacomms How does this look?
[Delivery Note Sample.pdf](https://github.com/openboxes/openboxes/files/4241796/Delivery.Note.Sample.pdf)

**Comment by pacomms** [comment]
Looks good m8, especially the comments section, is there a way to add the Toronto edit deli very address on a PO as well? In cases where we drop ship from a supplier direct to client ?

Looks good though , is this available now?

Thanks
Kurt

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pacomms** [comment]
Looks good m8, especially the comments section, is there a way to add the Toronto edit deli very address on a PO as well? In cases where we drop ship from a supplier direct to client ?

Looks good though , is this available now?

Thanks
Kurt


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jmiranda** [comment]
> is there a way to add the Toronto edit deli very address on a PO as well? In cases where we drop ship from a supplier direct to client ?

I'm not following. Can you elaborate on this request? And maybe provide an example using screenshots from the PO feature to describe how you'd like it to work?

>  is this available now?

No, it'll be available in the next release (which is still a few weeks away). I could point you to a pre-release version once I finalize the feature based on your feedback. But I'd recommend you testing that pre-release version thoroughly before deploying it because

**Comment by pacomms** [comment]
Looks good m8, especially the comments section, is there a way to add the
Toronto edit deli very address on a PO as well? In cases where we drop ship
from a supplier direct to client ?

Looks good though , is this available now?

Thanks
Kurt

Get Outlook for Android <https://aka.ms/ghei36>

------------------------------
*From:* Justin Miranda <notifications@github.com>
*Sent:* Sunday, February 23, 2020 5:08:58 PM
*To:* openboxes/openboxes <openboxes@noreply.github.com>
*Cc:* pacomms <kurt6459@gmail.com>; Mention <mention@noreply.github.com>
*Subject:* Re: [openboxes/openboxes] Add the ability for address in
delivery note (#1422)


@pacomms <https://github.com/pacomms> How does this look?
Delivery Note Sample.pdf
<https://github.com/openboxes/openboxes/files/4241796/Delivery.Note.Sample.pdf>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openboxes/openboxes/issues/1422?email_source=notifications&email_token=AJCSLEITUO3GFO3GJEGSFI3REKUSVA5CNFSM4KPUX6NKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMWBMKY#issuecomment-590091819>,
or unsubscribe

**Comment by jmiranda** [comment]
@pacomms Since it's a different feature can you add a new ticket for the additional request you made. I'm not exactly sure what you're asking for so please elaborate in the new ticket.

> is there a way to add the Toronto edit deli very address on a PO as well? In cases where we drop ship from a supplier direct to client ?
