### ISSUE TITLE
New contributor git instructions in Readme should be updated as command fails

### ISSUE THREAD

**Issue by ghost** [openboxes/openboxes#16]
<h3>Probable Cause:</h3>

SSH setup for accessing the repo not specified or TBD by administrator.

<h3>Command Output:</h3>

Shahri-MacBookPro:Repos Shahri$ git clone git@github.com:PIH/openboxes.git
Cloning into 'openboxes'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'''

**Comment by jmiranda** [comment]
I believe the instructions have been updated.
