### ISSUE TITLE
Can not start up Openboxes from tomcat7.0.90

### ISSUE THREAD

**Issue by Joy-Zhang-0303** [openboxes/openboxes#1609]
Hello, Openboxes team

When I start up this application from Tomcat app manager by right click the /openboxes.war icon, I can not start up application normaly. 
![Screenshot from 2020-04-24 01-50-57](https://user-images.githubusercontent.com/48177679/80126762-67d52300-85ce-11ea-860d-9bbe546560ba.png)
(**HTTP Status 404 – Not Found**). 
I need your help to share some ideas.

My environment: 
Docker + Release0.8.11 (Thanks to Justin-san help revising docker-compose file about tomcat version.)

Thanks and looking forward to your reply.
H.Z

**Comment by jmiranda** [comment]
@Joy-Zhang-0303 Can you upload the Tomcat logs?

**Comment by jmiranda** [comment]
Also, I think a better way of deploying the latest WAR file is to download the openboxes.war into the docker directory and then run ```docker-compose up``` or ```docker-compose up -d```
```
cd openboxes/docker
wget https://github.com/openboxes/openboxes/releases/latest/download/openboxes.war
docker-compose up -d
```

**Comment by Joy-Zhang-0303** [comment]
@jmiranda 
Justin-san, Thanks so much.
I have succefully start the application by using the way you said. 
Now I am enjoying Openboxes...
![Screenshot from 2020-04-24 10-58-28](https://user-images.githubusercontent.com/48177679/80167203-bc9e8b00-861a-11ea-9d09-b9cfecf27857.png)

**Comment by jmiranda** [comment]
@Joy-Zhang-0303 So glad you got it working. Best of luck and let us know if you have any feedback.

**Comment by Joy-Zhang-0303** [comment]
@jmiranda Sure, I will. Thank you, Justin-san.
