### ISSUE TITLE
Allow user to change barcode types between code39 and code128

### ISSUE THREAD

**Issue by XXyomerengues** [openboxes/openboxes#196]
Allow user to change barcode types between code39 and code128

**Comment by jmiranda** [comment]
Thanks again for creating the ticket @XXyomerengues. Just out of curiosity where (in the app) are you using barcodes? Would you like to see barcodes in more places? In other words, are we missing them in some features / documents? Do you want to be able to design and print barcode labels for items within the app? And lastly, would you be interested in helping to define some improvements to features that could utilize a more barcode-centric workflow?

**Comment by XXyomerengues** [comment]
Hi Justin,

The barcodes are useful on the Packing List (Pallet), code128 is easier to
read for scanners than code39 and supports alphanumeric characters (hence
the request); barcodes would also be useful to on the serial numbers. In
order to customize and be able to keep track on every incoming item easily,
designing and printing barcodes would be really helpful, (maybe a QR code
with the serial number or lot, date of receipt and item code for items
received/stored or even identify the type of material: hazardous,
quarantine, On-hand, etc.)

As for the improvements, I would be happy to help.
Best Regards
Jorge Reza

2017-05-03 13:02 GMT-05:00 Justin Miranda <notifications@github.com>:

**Comment by jmiranda** [comment]
As of v0.7.16 (to be released soon), OpenBoxes allows sys admins to configure barcode format (as well as default height and width) within the openboxes-config.properties. The following formats are "supported", but some of do not have an associated encoder within the barcode4j library so they fail. Formats that are known to work are CODE_39, CODE_128, and QR_CODE. If others are needed please create a new ticket to request support and we'll look into whether we can configure an appropriate encoder.

```# Supported formats: AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, UPC_EAN_EXTENSION;
openboxes.identifier.barcode.format = CODE_128
openboxes.identifier.barcode.height = 40
openboxes.identifier.barcode.width = 100
```
