### ISSUE TITLE
OB Property file location should be property driven.

### ISSUE THREAD

**Issue by ghost** [openboxes/openboxes#20]
## Outline:

In an attempt to leverage the white-boxing properties of the application the <b><i>app.name</i></b> property of the <b><i>application.properties</i></b> file was changed.
Regardless of the database connection settings in the <b><i>openboxes-config.properties</i></b> file, <b>unless</b> the app.name is set to <b><i>openboxes</i></b> the application fails to connect to the database.
## Screenshots:
1. Run with property set to openboxes (N.B. no changes to <b><i>openboxes-config.properties</i></b>):

![screen shot 2013-12-22 at 4 54 22 pm_obdefectwhitelabeling_1_of_2](https://f.cloud.github.com/assets/6078105/1797902/902bbbf6-6b19-11e3-99f7-5e9ca5c49d15.jpg)
1. Run with property set to something other (N.B. no changes to <b><i>openboxes-config.properties</i></b>):
   ![screen shot 2013-12-22 at 4 51 42 pm_obdefectwhitelabeling_2_of_2](https://f.cloud.github.com/assets/6078105/1797903/99c49d22-6b19-11e3-9a40-54f7e3877947.jpg)
## Properties Context:

There are multiple properties files.

**Comment by jmiranda** [comment]
This was completed as part of [Hotfix 0.7.14](https://github.com/openboxes/openboxes/releases/tag/v0.7.14).
