### ISSUE TITLE
inventory_item database table has no foreign key to inventory database table

### ISSUE THREAD

**Issue by ghost** [openboxes/openboxes#21]
## Outline:

Currently there is no way of attributing an inventory item to an inventory via the relationship between the following tables:
1. inventory_item
2. inventory

inventory_item only relates itself to a product using a foreign key and a product.

**Comment by jmiranda** [comment]
This ticket was more or less dealt with by the creation of the inventory_snapshot table which keeps a record of all current stock items for every product, date, and location combination. We also recently add product_availability which contains the current on hand stock data at the inventory item (lot number) level for all locations / sub locations.
