### ISSUE TITLE
Allow sysadmin to override grails.config.locations using command line argument or env property

### ISSUE THREAD

**Issue by ghost** [openboxes/openboxes#22]
## Outline:

It might not always be possible to setup a directory .grails in the Tomcat home in order to configure open-boxes due to operational restrictions. Given the fact that the data source specification and others reside in this properties file, without it the application (don't think) can connect to the underlying db.
## Solutions:

Hard coding a default solutions is not a good idea (in case the code can not find the properties).
Instead, and given the nature of a previous defect regarding properties files, this property fils should be amalgamated with the one in the application.properties file.
This way, deployment would become more streamlined.

**Comment by jmiranda** [comment]
I just realized that the commit above caused this ticket to close. However, we really want to be able to set these config locations from the command-line or system env property.
