### ISSUE TITLE
Build problem with putaway ( both grail 1.3.9 and 3.3.10)

### ISSUE THREAD

**Issue by khanhan2211** [openboxes/openboxes#2293]
i got an issue when running with grails 1.3.9 in **WINDOWS**. 

During the build, It creates 2 folder “putAway” and “putaway” in “target\classes\org\pih\warehouse\putAway” by 2 file PutAwayController.groovy, PutawayService.groovy.

Because the package name is difference “putaway” vs “putAway”. But as you know in Windows, you can’t create same folder name so it will cause an error during the build in windows environment.

**Comment by jmiranda** [comment]
Thanks, we'll try to refactor this soon.
