### ISSUE TITLE
Data refresh rate

### ISSUE THREAD

**Issue by IMiGS** [openboxes/openboxes#234]
Is it possible to create  or add some parameters to get a quicker refresh rate of data synchronization across the system?
For example, If I made some name changes in category names and then try to create a new product, information on category select field shows up the old information and it takes some X time till the changed name shows in product creation screen.
Another example that it doesn't automatically refresh Dashboard inventory stock screen when there is added X qty items in the storage.

Versions in use:
openboxes Release 0.7.27
Ubuntu 14.04
Tomcat7
MySQL 5.5

**Comment by jmiranda** [comment]
Yeah, let me look to see if there's a way to have user-defined TTL config for the data caches in resources.groovy
https://github.com/openboxes/openboxes/blob/develop/grails-app/conf/spring/resources.groovy

Alternatively, (and a more correct approach to this issue) is to evict elements of the cache that are updated. Unfortunately, we're using on older version Grails (and consequently an older version of the caching plugin) that doesn't seem to allow eviction at the record-level. It's either all or not. But even that would be better (cache refresh on any data changes) would be better than waiting 1 - 24 hours for the cache to refresh. I'll take a look in the next couple two tree days.

**Comment by IMiGS** [comment]
Thanks for looking into it!

**Comment by jmiranda** [comment]
It does look like we might be able to configure the caches via Config.groovy (overriding with openboxes-config.properties or openboxes-config.groovy). I am testing a few options and will add my findings here.

**Comment by jmiranda** [comment]
See the springcache docs for more details.
http://gpc.github.io/grails-springcache/docs/manual/guide/single.html#7. Cache Configuration

Moving the configuration from resources.groovy to Config.groovy allows us to override cache configuration properties. The defaults live in Config.groovy and can be overridden using openboxes-config.properties or openboxes-config.groovy

So for example if I wanted to change the TTL and a few other properties of the cache used for most of the data points on the dashboard page, my openboxes-config.properties might look like this. This means that a cached entry will live for as long as two minutes, but will be refreshed after 60 seconds if there hasn't been a cache hit for the entry. 
```
springcache.caches.dashboardCache.timeToLive = 120
springcache.caches.dashboardCache.timeToIdle = 60
springcache.caches.dashboardCache.memoryStoreEvictionPolicy = LFU
springcache.caches.dashboardCache.diskPersistent = true
```
