### ISSUE TITLE
Mark as consumed

### ISSUE THREAD

**Issue by antonio-guillen** [openboxes/openboxes#24]
When you click on "Mark as consumed" the next windows show all lots of items even if lots have not stock. If you have a lot of lots, this is not user-friendly.

"Consumption Window" will be more user-friendly if will not show the unnecessary items.

![20140807_20 14 24_selection](https://cloud.githubusercontent.com/assets/726710/3846693/ed2d933a-1e5e-11e4-825f-bac18d3773ac.png)

"Consumption Window":
![20140807_19 53 14_selection](https://cloud.githubusercontent.com/assets/726710/3846617/5439d440-1e5e-11e4-9c58-89287812506a.png)

**Comment by jmiranda** [comment]
![image](https://user-images.githubusercontent.com/1162935/110009543-c2f19f00-7ce2-11eb-9a7e-eca223796bef.png)
