### ISSUE TITLE
User rights not pulling trough corectly

### ISSUE THREAD

**Issue by MischaSLabbert** [openboxes/openboxes#241]
Good day

After some testing we found a bug in the roles of users.

In the test scenario we have created two warehouse locations. The locations are based on how the products in the warehouse is processed. 
The first location is our Quarantine location, and the second is the main warehouse, where all final dispatching will come from. We have also created a user with assistant role assigned to it.
The location roles for the assistant User is as follow:
•	Main Warehouse location   	-  	Browser Role
•	Quarantine Location		-	Default

The scenario states that the assistant users default warehouse/location is the Quarantine Location, and this user will be allowed to receive shipment into the Quarantine Location, to go trough a QA process. The Once the QA process was successful, the stock will then be moved to the Main Warehouse/Location via the Quarantine Location Assistant User, by creating a outbound shipment. On the other side the Main Warehouse will also have an assistant user, who will be receiving the shipments.

However both the assistants, regardless of the location Roles setup in the user setup, can create and receive shipments on both locations.

Can you please investigate and revert back.

If it is possible we would like to somehow disable the assistant user from the Quarantine Location, to select the Main warehouse at time of login, or even change to it in a session, and vise versa for the Main Warehouse Assistant User. (In fact for any user role, to disable a location for a user)

Kind regards

**Comment by jmiranda** [comment]
Thanks @MischaSLabbert

**Comment by jmiranda** [comment]
I just had some time to look into this and fixed a few issues. Still some work to do, but I think the next version will include a fix for your needs.
https://drive.google.com/file/d/1-dRiDcS6AKGO6FczBUp1--X0jmRGpTNh/view

**Comment by jmiranda** [comment]
I've also added a new ticket for the second part of this ticket #244

**Comment by jmiranda** [comment]
The first part of this ticket should be fixed in release 0.7.29.
