### ISSUE TITLE
Error on shipment send

### ISSUE THREAD

**Issue by rudolf992** [openboxes/openboxes#2592]
Hello,

I am new to openboxes, having an issue when doing inbound process. The shipment can not be sent and received. Couldn't find where to look for the error. Error appears when I press Send Shipment.

Thank you!

![image](https://user-images.githubusercontent.com/32765188/130181674-65348004-f527-4cae-9157-43f96852f112.png)

**Comment by jmiranda** [comment]
Thanks for the bug report @rudolf992. I assume this is happening while trying to send the email notification for the shipped event.

To confirm, I'll need to see the stracktrace that gets written to the log file. Assuming you've installed on Ubuntu can you tail the log file and then try to send the shipment again. Then copy and paste the log messages and post them here. 
```
tail -f /opt/tomcat/logs/catalina.out
```

As a workaround you can disable email by adding / modifying the grails.mail.enabled property and setting it to false.
```
grails.mail.enabled = false
````

**Comment by rudolf992** [comment]
Yes I have installed on ubuntu. Catalina.out started to show the errors after creating a file logging.properties with the following content and placed it inside Apache-tomcat\webapps\MyApp\WEB-INF\classes and restart the Apache Tomcat server.

`org.apache.catalina.core.ContainerBase.[Catalina].level=INFO
org.apache.catalina.core.ContainerBase.[Catalina].handlers=java.util.logging.ConsoleHandler`

`2021-08-20 17:45:59,729 [http-bio-8080-exec-4] INFO  core.UserService  - Is role ROLE_ADMIN in [ROLE_SUPERUSER, ROLE_ADMIN] = true
2021-08-20 17:45:59,731 [http-bio-8080-exec-4] INFO  core.MailService  - Sending email with subject Shipment 665RSV has been shipped to [admin@openboxes.com] from info@openboxes.com        via localhost:25
2021-08-20 17:45:59,731 [http-bio-8080-exec-4] INFO  core.MailService  - Mail is enabled
2021-08-20 17:45:59,731 [http-bio-8080-exec-4] INFO  core.MailService  - Sending html email 'Shipment 665RSV has been shipped' to [admin@openboxes.com]
2021-08-20 17:45:59,749 [http-bio-8080-exec-4] ERROR core.MailService  - Error sending HTML email message with subject Shipment 665RSV has been shipped to [admin@openboxes.com]
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1398)`


Problem was due to mail system setup. Your solution solved the problem. 

Thank you!

**Comment by jmiranda** [comment]
@rudolf992 Awesome. Let me know if there's anything else. 

If you need help getting familiar with the system checkout the following resources:

- Documentation https://docs.openboxes.com
- User Guide https://openboxes.atlassian.net/wiki/spaces/OBW/overview
- Discussion forum https://discuss.openboxes.com/

General questions about features / functionality can be posted to the discussion forum or emailed to discuss@openboxes.com.
