### ISSUE TITLE
grails command has error

### ISSUE THREAD

**Issue by majidln** [openboxes/openboxes#277]
when I enter grails upgrade command, below error raised:

```| Error Error occurred running Grails CLI: null (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)

java.lang.NullPointerException
	at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:516)
	at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:307)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:270)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: null
```

what is the problem? what is the solution?

**Comment by jmiranda** [comment]
From the stacktrace it appears to be a more recent version, like Grails 3. Can you let me know what version of Grails you're using here? 

Unfortunately, we're stuck on Grails 1.3.9 for the time being. But you can use Sdkman to install and use different versions of Grails.

http://sdkman.io/install.html

Once you follow the installation instructions, it's as simple as:
```
sdk use grails 1.3.9 
```

Let me know if you have further questions.

**Comment by jmiranda** [comment]
Closing as the previous comment answered the question. However, if someone were to stumble onto this before we finished the Grails 3 migration and wanted to run Grails 3 on our code base there's a long-lived feature branch housing all of the migration changes here. 
https://github.com/openboxes/openboxes/tree/feature/upgrade-to-grails-3.3.10
