### ISSUE TITLE
Resource Not Found error on Stock Transfer

### ISSUE THREAD

**Issue by DavidBaldwin1015** [openboxes/openboxes#2914]
I keep getting a Resource Not Found error when trying to create a new stock transfer. The Catalina logs show something about a handleNotFound error.

![Screenshot from 2022-01-17 13-27-11](https://user-images.githubusercontent.com/33533043/149827908-6cd09095-9e8e-4e7b-807f-bd2b95880859.png)

![Screenshot from 2022-01-17 13-30-10](https://user-images.githubusercontent.com/33533043/149827927-443c2c8c-c1ce-424a-815f-d5b44537e272.png)

![Screenshot from 2022-01-17 13-31-35](https://user-images.githubusercontent.com/33533043/149828996-9585ce7a-3203-4683-92e6-e1dbceec96ff.png)

**Comment by jmiranda** [comment]
Hey @DavidBaldwin1015. Thank you for the bug report and screenshots. And sorry for the delay. 

This is a weird issue. To my knowledge we have not encountered this before. Could you do an right click > Inspect, refresh the screen and let me know what resources are returning status = 404.

![image](https://user-images.githubusercontent.com/1162935/150022998-dd163dd7-1d95-4aea-b3b2-1b44d266b846.png)

**Comment by ddouma** [comment]
Same issue here!

**Comment by jmiranda** [comment]
@ddouma Thanks for the confirmation.

If you want to test out the latest stable release you can download the WAR file here and see if that fixes the issue.
https://bamboo.pih-emr.org/browse/OPENBOXES-DMB/latest/artifact

And follow the upgrae instructions here
https://docs.openboxes.com/en/latest/upgrading/

IMPORTANT: I would recommend backing up your database before doing the upgrade just in case there are any issues with the automated database migrations that are executed during the startup process.

cc @DavidBaldwin1015

**Comment by ddouma** [comment]
Fixed!
