### ISSUE TITLE
Launched application Z-order

### ISSUE THREAD

**Issue by alexzk1** [openboxes/openboxes#2971]
I'm not sure if it issue or request to help of "how to do".
Well, my problem is ...I launch some long-starting-application. For example, google-chrome. It takes 5-10-15 seconds before window appear.
So I keep typing let's say in text editor. Then finally new window appears and aggressively interrupts me. Sometimes twice, because I do alt-tab on reflexes and it pops 2nd time.

So my question is, is any way to force such new windows to sit below current in z-order and do not interrupt me IF me is typing / using mouse. If no user input last 500ms it could pop normal to top. I think this is including any pop-ups of any already running window, but not sure 100% as I disabled any pop up I could find in system. But would be cool to keep it below too.

I was trying to figure why I do that, I think old MS Windowses like XP and below had such behave, so I got a habit.

**Comment by jmiranda** [comment]
Hey @alexzk1 Thank you for the ticket. However, I'm wondering if maybe you're looking for openbox (https://en.wikipedia.org/wiki/Openbox) the window manager, not OpenBoxes, the inventory management system.
