### ISSUE TITLE
Custom Report

### ISSUE THREAD

**Issue by sm2x** [openboxes/openboxes#436]
How to add a new custom report?
or Run an Ad-hoc one?

Any user guide or user manual available even a Quick summarized step-by-step guide from initial setup to day-to-day activities:
1.  Receiving to put away.
2.  Request to pick list to shipping and tracking.
3.  Weekly physical inventory.

Regards and thank you.

**Comment by jmiranda** [comment]
@sm2x Thanks for the questions. 

> How to add a new custom report?

There's no custom report feature at the moment, but you can access the MySQL instance using a third-party reporting tool to build your own custom reports. Example reporting systems include but are not limited to BIRT Reporting, JasperReports, Pentaho, Tableau, Talend, JetReports, etc.

We're currently building some dimensional schemas (i.e. data warehouse) within OpenBoxes to help support more complex reporting. But if there's a specific report you're looking for please let us know and we can try to help figure out a possible solution.

> or Run an Ad-hoc one?

Can you clarify what you mean by "run an ad-hoc one"?

> Any user guide or user manual available even a Quick summarized step-by-step guide from initial setup to day-to-day activities:

I'll try to put together a quick tutorial video when I get a chance.

**Comment by sm2x** [comment]
Adhoc, meaning a report based on SQL Query, I can save for later use, then a possibility to export to CSV or spreadsheet.

Even a flowchart of activities will do,
- initial setup (steps, what to setup and configure first)
- sample receiving to putaway
- sample  request to shipping to tracking
This will help us, at least those who are complete beginner on implementing a system like OB.

**Comment by jmiranda** [comment]
@sm2x Agreed. I've been meaning to write a comprehensive user guide for some time. In the meantime, if you'd like a quick walk-through, please schedule a demo (https://calendly.com/openboxes/demo) and I can go through a bunch of the configuration steps and features.

**Comment by jmiranda** [comment]
@sm2x I forgot to update this ticket, but we now have support for custom reports from within OpenBoxes.

https://watch.screencastify.com/v/WryohTVED5vbZ1rFQBCM
